language: java
notifications:
  slack:
    secure: CxsemFau+mBbtB/r+k8GMeT+K/nOoLXGTVfLtkVh374AUp4s29qT4acn6eVpdNPNbDyk9oKqbLlccp/G8C601wL3ZOlTo4vYOmvir6USGPvgLtGCJe6ObnmV6GvPMPilGUm80dH2y41bPgcr0env8uPAKTwz9TT7IHRED2EiF+I=
