language: java
notifications:
  slack:
    secure: IQdjoLlyS+p0NLlguni6V594nG7Yr6RI0YHJ/d19ITZ/6sGTtSxgUL1ekT8O0eBqjg7MtyPX35xioHA3QkklX5Sqh7dBCByChjegQApxTjsSRp7oB/mzaVGNbmWRXNOUEi/8INP+HAaBoHv722WHTbaYNm4ZEnhtWA0v6HpW5Fs=
